platform-api docker config initial stage
BeeQuantAI/platform_api pull request #12
Opened 2024-04-04 13:25 UTC by hulinpiao

**The changes introduced in this Pull Request include:**

- [x] Creation of a Dockerfile to containerize the platform_api resources.
- [x] Configuration of the database connection using Docker networking.
- [x] Updates to related configurations and operational steps in the README.md.

2024-04-04 13:30 UTC, hulinpiao commented on Dockerfile
> +CMD ["yarn", "start"]
To whom review it：
it is initial docker config step, which simply run docker on localhost. so, I've only run 'yarn start' command for initial docker setup. However, we should consider the code build, test, format etc before the service running.

2024-04-07 14:40 UTC, hulinpiao commented
@Chris-Wang , I found this "platform_api" repo can request up to 1 reviewer for PR. 
can we get more people to review the MR ? I would like to get review from other devops colleagues.

2024-04-08 07:31 UTC, Chris-Wang requested changes

2024-04-08 07:31 UTC, Chris-Wang commented on README.md
> +   docker network create platform_api
is this step essential for local development, if not, please consider marking it as `optional` with some comments

2024-04-08 07:31 UTC, Chris-Wang commented on Dockerfile
> +FROM node:20.10
same as frontend, consider using `alpine`?

2024-04-08 07:31 UTC, Chris-Wang commented on Dockerfile
> +RUN yarn install
you can keep it aligned with your frontend docker file by removing `install`

2024-04-08 07:31 UTC, Chris-Wang commented on tsconfig.json
please leave comments why some of the config and their order has been changed?

2024-04-08 07:31 UTC, Chris-Wang commented on src/app.module.ts
lack adding DB_HOST in env

2024-04-09 13:47 UTC, hulinpiao commented on tsconfig.json
I have sorted the JSON values/parameters in alphabetical order, as it is a good practice to organize parameters in configuration files. As a side note, the extension I use for sorting JSON and YAML files is called 'Sort Everything.'

2024-04-09 13:48 UTC, hulinpiao commented on Dockerfile
> +RUN yarn install
removed

2024-04-09 13:48 UTC, hulinpiao commented on Dockerfile
> +FROM node:20.10
done.

2024-04-09 13:50 UTC, hulinpiao commented on src/app.module.ts
You're right, Chris. The update didn't push because .gitignore prevents .env from merging into the remote repository. I'll update the README.md file to include a note about adding DB_HOST

2024-04-09 14:23 UTC, hulinpiao commented on README.md
> +   docker network create platform_api
It's not particularly useful for local development work. 
However, this step is vital for dockerizing the backend and connecting it to the DB container locally, a process that can also aid in preparing for cloud deployment through dockerization. 

Following your suggestion, I’ve marked it as optional and included some comments for clarification.

2024-04-14 21:40 UTC, Chris-Wang requested changes
Await Readme to be updated as discussed

2024-04-20 13:30 UTC, Chris-Wang requested changes
Need:
- pull latest dev to your branch, some code is duplicated
- resolve conflict
- squash commits after merge latest dev

2024-04-21 04:34 UTC, hulinpiao commented
> Need:
> 
> * pull latest dev to your branch, some code is duplicated
> * resolve conflict
> * squash commits after merge latest dev

Thanks.  solved the duplicated.

2024-04-21 06:04 UTC, Chris-Wang approved these changes
LGTM

2024-04-21 06:04 UTC, merged