feat: exchange connection
BeeQuantAI/platform_api pull request #35
Opened 2024-06-15 23:52 UTC by Flysmallsheep

feat: add exchange connection capability

- Implemented the ability for users to create a new exchange connection with a provided API key and secret key.
- Verifies the API key from the selected exchange (Binance) during the connection creation process.
- If the API key verification is successful, the user exchange connection with the exchange keys are created and stored.
- Added functionality to send a success message "Cool! Your exchange key is added successfully!" upon successful creation of the connection.
- Displays a fault message on the field if the API key verification fails or any other error occurs.

Resolve CP-18

<img width="2054" alt="工作  Lucidchart Google Chrome, Today at 9 40 02 am" src="https://github.com/BeeQuantAI/platform_api/assets/29514745/d6c0a3c9-79c4-49bf-9bb9-c68345ab24d8">

<img width="1534" alt="user_exchange resolver spec ts — platform_api Code, Today at 9 46 15 am" src="https://github.com/BeeQuantAI/platform_api/assets/29514745/5a63c5b5-f31f-4deb-91d4-37491e5275b9">
<img width="2536" alt="Playground - http --localhost 3000-graphql Google Chrome, Today at 9 48 24 am" src="https://github.com/BeeQuantAI/platform_api/assets/29514745/c4e8313b-dd7b-4396-a5a8-b65bd25a8267">
<img width="2544" alt="Google Chrome Google Chrome, Today at 9 49 15 am" src="https://github.com/BeeQuantAI/platform_api/assets/29514745/8757bcf1-044a-4641-9eee-4b0759eeb814">
<img width="2534" alt="Playground - http --localhost 3000-graphql Google Chrome, Today at 9 50 07 am" src="https://github.com/BeeQuantAI/platform_api/assets/29514745/e3e197c5-6590-45c4-ba7e-6109f6597913">

2024-06-16 00:04 UTC, Flysmallsheep commented
Added feature:

Implemented the ability to fetch all user connection balances for the authenticated user. This includes:

- Retrieving the balances of all user exchange connections.
- Filtering out zero balances and returning only the coins with non-zero balances.
- Returning the balances along with the corresponding user exchange connection details.

2024-06-16 02:14 UTC, Chris-Wang requested changes
- return message should be more subjective, it should only tell the state of the request
- all our return should follow `code`, `message`, `data` pattern, includes error return
- please merge the latest dev to your branch
- please fix lint issue:
![Uploading image.png…]()

2024-06-16 02:14 UTC, Chris-Wang commented on src/modules/user_exchange/user_exchange.service.ts
> +        message: 'Cool! Your exchange key is added successfully!',
the return message should be more subjective, since we're not using it directly to rending on client

2024-06-16 02:14 UTC, Chris-Wang commented on src/modules/user_exchange/user_exchange.service.ts
> +        success: true,
all return should come with `code` and `message`, we don't return `success`

2024-06-16 02:16 UTC, Chris-Wang commented
<img width="499" alt="image" src="https://github.com/BeeQuantAI/platform_api/assets/1610136/4bbfdb9f-a6e3-40cb-96eb-e175f54e5513">

- and squash commits

2024-06-19 08:15 UTC, Chris-Wang requested changes
Needs to:
- squash commits
- resolve previous comments
- we don't use `_` for folder or module name, consider renaming it to userExchange or user-exchange
- remove commented code

2024-06-19 08:15 UTC, Chris-Wang commented on src/modules/user_exchange/user_exchange.resolver.ts
> +  // TODO: template for exchangeManagement, updateExchange and deleteExchange tickets
commented code should not exist in code base unless it's necessary

2024-09-09 00:08 UTC, Chris-Wang approved these changes
LGTM

2024-09-09 00:08 UTC, merged